name: dump_issues
run-name: ${{ github.actor }} is dumping issues
on: workflow_dispatch
jobs:
  dump-all-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          MAX_NUM=$(gh issue list -R "${REPO}" --limit 1 --json number | jq ".[].number"); 
          echo $MAX_NUM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        
